/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sujajeb
 */
public class Aresta extends javax.swing.JDialog {

    java.awt.Frame pai;
    private DefaultTableModel modelo = new DefaultTableModel();
    private DefaultListModel model = new DefaultListModel();
    private List<Node> vertices = new ArrayList<Node>();
    private List<Edge> arestas = new ArrayList<Edge>();
    private String xml1 = null;
    private String choose = null;
    private String head = "<? Xml version = \"1.0\" encoding = \"UTF-8\"?>\n"
            + "<GraphML xmlns = \"http://graphml.graphdrawing.org/xmlns\"  \n"
            + "    xmlns: xsi = \"http://www.w3.org/2001/XMLSchema-instance\"\n"
            + "    xsi: schemaLocation = \"http://graphml.graphdrawing.org/xmlns \n"
            + "    ' http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd \'>";
    private String id, edgedefault;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEdgedefault() {
        return edgedefault;
    }

    public void setEdgedefault(String edgedefault) {
        this.edgedefault = edgedefault;
    }

    public void setChoose(String choose) {
        this.choose = choose;
    }

    public String getChoose() {
        return choose;
    }

    /**
     * Creates new form FrmCadClienteModal
     */
    public Aresta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pai = parent;
        initComponents();
        modelo.addColumn("Nome");
        modelo.addColumn("1º Vertice");
        modelo.addColumn("2º Vertice");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        FileChooser = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaArestas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        PainelAresta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listaNode02 = new javax.swing.JComboBox<>();
        listaNode01 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CriarAresta = new javax.swing.JButton();
        EditarAresta = new javax.swing.JButton();
        removerAresta = new javax.swing.JButton();
        limparTextoAresta = new javax.swing.JButton();
        nomeAresta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PainelXML = new javax.swing.JPanel();
        abrirXML = new javax.swing.JButton();
        url = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gerarXml = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        criarNo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeVertice = new javax.swing.JTextField();
        editarVertice = new javax.swing.JButton();
        removerVertice = new javax.swing.JButton();
        limparTextoVertice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVertices = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        FileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\negro\\Desktop"));
        FileChooser.setDialogTitle("Esta é minha caixa aberta");
        FileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de alunos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Cadastro de Vertices e Arestas");

        tabelaArestas.setAutoCreateRowSorter(true);
        tabelaArestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaArestas.setFont(tabelaArestas.getFont().deriveFont((tabelaArestas.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, tabelaArestas.getFont().getSize()+7));
        tabelaArestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "1º VERTICE", "2º VERTICE"
            }
        ));
        tabelaArestas.setGridColor(new java.awt.Color(102, 102, 102));
        tabelaArestas.getTableHeader().setResizingAllowed(false);
        tabelaArestas.getTableHeader().setReorderingAllowed(false);
        tabelaArestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaArestasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaArestas);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Lista de Arestas");

        PainelAresta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Selecione os Vertices da Aresta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("2º Nó ");

        listaNode02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNode02MouseClicked(evt);
            }
        });

        listaNode01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaNode01MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("1º Nó ");

        CriarAresta.setBackground(new java.awt.Color(153, 153, 255));
        CriarAresta.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        CriarAresta.setText("Criar Aresta");
        CriarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarArestaActionPerformed(evt);
            }
        });

        EditarAresta.setBackground(new java.awt.Color(255, 255, 204));
        EditarAresta.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        EditarAresta.setText("Editar");
        EditarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        removerAresta.setBackground(new java.awt.Color(255, 102, 102));
        removerAresta.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        removerAresta.setText("Remover");
        removerAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerArestaActionPerformed(evt);
            }
        });

        limparTextoAresta.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        limparTextoAresta.setText("Limpar");
        limparTextoAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTextoArestaActionPerformed(evt);
            }
        });

        nomeAresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeArestaMouseClicked(evt);
            }
        });
        nomeAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeArestaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome da Aresta");

        javax.swing.GroupLayout PainelArestaLayout = new javax.swing.GroupLayout(PainelAresta);
        PainelAresta.setLayout(PainelArestaLayout);
        PainelArestaLayout.setHorizontalGroup(
            PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelArestaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PainelArestaLayout.createSequentialGroup()
                .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelArestaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelArestaLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(listaNode02, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(PainelArestaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16)
                                .addComponent(listaNode01, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12))
                    .addGroup(PainelArestaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(EditarAresta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limparTextoAresta)
                            .addComponent(nomeAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CriarAresta)
                    .addComponent(removerAresta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PainelArestaLayout.setVerticalGroup(
            PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelArestaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelArestaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaNode01, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaNode02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36))
                    .addGroup(PainelArestaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CriarAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeAresta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PainelArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarAresta)
                    .addComponent(limparTextoAresta)
                    .addComponent(removerAresta))
                .addGap(30, 30, 30))
        );

        PainelArestaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditarAresta, limparTextoAresta, removerAresta});

        PainelXML.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        abrirXML.setBackground(new java.awt.Color(255, 255, 204));
        abrirXML.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        abrirXML.setText("Abrir XML");
        abrirXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirXMLActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Local do Arquivo");

        gerarXml.setBackground(new java.awt.Color(204, 255, 204));
        gerarXml.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        gerarXml.setText("Gerar XML");
        gerarXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarXmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelXMLLayout = new javax.swing.GroupLayout(PainelXML);
        PainelXML.setLayout(PainelXMLLayout);
        PainelXMLLayout.setHorizontalGroup(
            PainelXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelXMLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(PainelXMLLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PainelXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abrirXML)
                    .addComponent(gerarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PainelXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelXMLLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abrirXML, gerarXml});

        PainelXMLLayout.setVerticalGroup(
            PainelXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelXMLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(abrirXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gerarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelXMLLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {abrirXML, gerarXml});

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        criarNo.setBackground(new java.awt.Color(153, 153, 255));
        criarNo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        criarNo.setText("Criar Vértice");
        criarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarNoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Nome do Vértice:");

        editarVertice.setBackground(new java.awt.Color(255, 255, 204));
        editarVertice.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        editarVertice.setText("Editar");
        editarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarVerticeActionPerformed(evt);
            }
        });

        removerVertice.setBackground(new java.awt.Color(255, 102, 102));
        removerVertice.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        removerVertice.setText("Remover");
        removerVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerVerticeActionPerformed(evt);
            }
        });

        limparTextoVertice.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        limparTextoVertice.setText("Limpar");
        limparTextoVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTextoVerticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removerVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(limparTextoVertice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(criarNo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel1))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(criarNo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(limparTextoVertice)
                .addGap(18, 18, 18)
                .addComponent(editarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerVertice)
                .addGap(19, 19, 19))
        );

        listaVertices.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        listaVertices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaVerticesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaVertices);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Lista de Vertices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelAresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PainelXML, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelAresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarArestaActionPerformed
        // TODO add your handling code here:
        Edge aresta = new Edge();
        aresta.setNome(nomeAresta.getText());
        aresta.setNode1(vertices.get(listaNode01.getSelectedIndex()));
        aresta.setNode2(vertices.get(listaNode02.getSelectedIndex()));
        tabelaArestas.setModel(modelo);
        modelo.addRow(new Object[]{nomeAresta.getText(), aresta.getNode1().getId(), aresta.getNode2().getId()});
        arestas.add(aresta);
        nomeAresta.setText("");
    }//GEN-LAST:event_CriarArestaActionPerformed

    private void limparTextoArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTextoArestaActionPerformed
        // TODO add your handling code here:
        nomeAresta.setText("");
        nomeAresta.setText("");
    }//GEN-LAST:event_limparTextoArestaActionPerformed

    private void removerArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerArestaActionPerformed
        // TODO add your handling code here:
        int index = tabelaArestas.getSelectedRow();
        if ((modelo.getRowCount() > 0) && (index >= 0)) {
            arestas.remove(index);
            Object remove;
            remove = modelo.getValueAt(index, 0);
            modelo.removeRow(index);
            nomeAresta.setText("");
            nomeAresta.setText("");
            JOptionPane.showMessageDialog(null, remove.toString() + " foi removido com sucesso ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma aresta ");
        }
    }//GEN-LAST:event_removerArestaActionPerformed

    private void listaNode01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNode01MouseClicked
        // TODO add your handling code here:
        listaNode01.removeAllItems();
        for (Node obj : vertices) {
            listaNode01.addItem(obj.getId());
    }//GEN-LAST:event_listaNode01MouseClicked
    }
    private void tabelaArestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaArestasMouseClicked
        // TODO add your handling code here:
        int index = tabelaArestas.getSelectedRow();
        if ((modelo.getRowCount() > 0) && (index >= 0)) {
            nomeAresta.setText(arestas.get(index).getNome());
            nomeAresta.setText(arestas.get(index).getNome());
            listaNode01.removeAllItems();
            listaNode01.addItem(arestas.get(index).getNode1().getId());
            listaNode02.removeAllItems();
            listaNode02.addItem(arestas.get(index).getNode2().getId());
        }

    }//GEN-LAST:event_tabelaArestasMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        int index = tabelaArestas.getSelectedRow();

        if ((modelo.getRowCount() > 0) && (index >= 0)) {
            Object teste = listaNode02.getSelectedItem();
            System.out.println(teste);
            teste = listaNode02.getSelectedItem().toString();
            System.out.println(teste);
            arestas.get(index).setNode1(vertices.get(listaNode01.getSelectedIndex()));
            arestas.get(index).setNode2(vertices.get(listaNode02.getSelectedIndex()));
            // arestas.get(index).setNome(nome);
            modelo.removeRow(index);
            modelo.insertRow(index, new Object[]{nomeAresta.getText(), arestas.get(index).getNode1().getId(), arestas.get(index).getNode2().getId()});
            nomeAresta.setText("");
            nomeAresta.setText("");
            Object edit;
            edit = modelo.getValueAt(index, 0);
            JOptionPane.showMessageDialog(null, "A Aresta " + edit.toString() + " foi editado com sucesso ");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma aresta ");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void gerarXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarXmlActionPerformed
        // TODO add your handling code here:
        JFileChooser arquivo = new JFileChooser();
        FileNameExtensionFilter filtroXML = new FileNameExtensionFilter("Arquivos XML", "xml");
        arquivo.addChoosableFileFilter(filtroXML);
        arquivo.setAcceptAllFileFilterUsed(false);
        if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            url.setText(arquivo.getSelectedFile().getAbsolutePath());
            choose = url.getText();
        }

        try {
            XStream xstream = new XStream(new DomDriver());
            String xml = xstream.toXML(arestas);
            System.out.println(xml);
            File file = new File(choose + ".xml");
            PrintWriter print = new PrintWriter(file);
            print.write(xml);
            print.flush();
            print.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Aresta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gerarXmlActionPerformed

    private void abrirXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirXMLActionPerformed
        JFileChooser arquivo = new JFileChooser();
        FileNameExtensionFilter filtroXML = new FileNameExtensionFilter("Arquivos XML", "xml");
        arquivo.addChoosableFileFilter(filtroXML);
        arquivo.setAcceptAllFileFilterUsed(false);
        if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            url.setText(arquivo.getSelectedFile().getAbsolutePath());
            choose = url.getText();
            try {
                // TODO add your handling code here:

                FileReader leitor = new FileReader(choose);
                XStream xstream = new XStream(new DomDriver());
                this.tabelaArestas.setModel(modelo);
                while (modelo.getRowCount() > 0) {
                    modelo.removeRow(0);
                }
                arestas = (ArrayList) xstream.fromXML(leitor);
                for (Edge inserir : arestas) {
                    modelo.addRow(new Object[]{inserir.getNome(), inserir.getNode1().getId(), inserir.getNode2().getId()});
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Aresta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_abrirXMLActionPerformed

    private void criarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarNoActionPerformed
        // TODO add your handling code here:
        Node no = new Node();
        listaVertices.setModel(model);
        model.removeAllElements();
        if (nomeVertice.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um nome para o Vértice ");
        } else {
            no.setId(nomeVertice.getText());
            vertices.add(no);
            nomeVertice.setText("");
            for (Node vertice : vertices) {
                model.addElement(vertice.getId());
            }
        }
    }//GEN-LAST:event_criarNoActionPerformed

    private void editarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarVerticeActionPerformed
        // TODO add your handling code here:        
        int index = listaVertices.getSelectedIndex();
        if ((vertices.size() > 0) && (index >= 0)) {

            String nome = nomeVertice.getText();
            if (nome.equals("")) {
                JOptionPane.showMessageDialog(null, "Selecione um nome para o Vértice ");
            } else {
                vertices.get(index).setId(nome);
                nomeVertice.setText("");

                JOptionPane.showMessageDialog(null, "O Vertice " + nome + " foi editado com sucesso ");
                model.removeAllElements();

                for (Node vertice : vertices) {
                    model.addElement(vertice.getId());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Vertice ");
        }
    }//GEN-LAST:event_editarVerticeActionPerformed

    private void listaVerticesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaVerticesMouseClicked
        // TODO add your handling code here:
        int index = listaVertices.getSelectedIndex();
        if (index >= 0) {
            nomeVertice.setText(vertices.get(index).getId());
        }
    }//GEN-LAST:event_listaVerticesMouseClicked

    private void listaNode02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaNode02MouseClicked
        // TODO add your handling code here:
        listaNode02.removeAllItems();
        for (Node obj : vertices) {
            listaNode02.addItem(obj.getId());
        }
    }//GEN-LAST:event_listaNode02MouseClicked

    private void removerVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerVerticeActionPerformed
        // TODO add your handling code here:
        int index = listaVertices.getSelectedIndex();
        System.out.println(index);
        if ((vertices.size() > 0) && (index >= 0)) {
            vertices.remove(index);
            Object remove;
            remove = model.get(index).toString();
            model.remove(index);
            nomeVertice.setText("");
            JOptionPane.showMessageDialog(null, "O Vertice " + remove + " foi removido com sucesso ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Vertice ");
        }
    }//GEN-LAST:event_removerVerticeActionPerformed

    private void nomeArestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeArestaMouseClicked
        // TODO add your handling code here:   

        int index01 = listaNode01.getSelectedIndex();
        int index02 = listaNode02.getSelectedIndex();
        String nome = (String) (vertices.get(index01).getId() + vertices.get(index02).getId());
        nomeAresta.setText(nome);
    }//GEN-LAST:event_nomeArestaMouseClicked

    private void limparTextoVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTextoVerticeActionPerformed
        // TODO add your handling code here:
        nomeVertice.setText("");
    }//GEN-LAST:event_limparTextoVerticeActionPerformed

    private void nomeArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeArestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeArestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aresta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aresta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aresta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aresta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Aresta dialog = new Aresta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    class MyCustomFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".xml");
        }

        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.xml)";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarAresta;
    private javax.swing.JButton EditarAresta;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JPanel PainelAresta;
    private javax.swing.JPanel PainelXML;
    private javax.swing.JButton abrirXML;
    private javax.swing.JButton criarNo;
    private javax.swing.JButton editarVertice;
    private javax.swing.JButton gerarXml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limparTextoAresta;
    private javax.swing.JButton limparTextoVertice;
    private javax.swing.JComboBox<String> listaNode01;
    private javax.swing.JComboBox<String> listaNode02;
    private javax.swing.JList<String> listaVertices;
    private javax.swing.JTextField nomeAresta;
    private javax.swing.JTextField nomeVertice;
    private javax.swing.JButton removerAresta;
    private javax.swing.JButton removerVertice;
    private javax.swing.JTable tabelaArestas;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
