/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Disciplina;

/**
 *
 * @author Sujajeb
 */
public class FrmCadAlunoModal extends javax.swing.JDialog {

    java.awt.Frame pai;
    private final DefaultListModel modelA = new DefaultListModel();
    private DefaultTableModel modelo = new DefaultTableModel();
    private final List alunos = new ArrayList<Aluno>();
    private List<Disciplina> disciplinasAluno = Disciplina.getDisciplinas();

    /**
     * Creates new form FrmCadClienteModal
     */
    public FrmCadAlunoModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pai = parent;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        GravarAluno = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cadastrarDisciplina = new javax.swing.JButton();
        limparAlunos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        anoAluno = new javax.swing.JTextField();
        gerarXml = new javax.swing.JButton();
        removerAluno = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        fechar = new javax.swing.JButton();
        listabox = new javax.swing.JComboBox<>();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de alunos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Ano:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Nome:");

        nomeAluno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        GravarAluno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        GravarAluno.setText("Gravar");
        GravarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Disciplina:");

        cadastrarDisciplina.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cadastrarDisciplina.setText("Cadastrar Disciplina");
        cadastrarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamarTelaCadDisciplina(evt);
            }
        });

        limparAlunos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        limparAlunos.setText("Limpar");
        limparAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Cadastro de Alunos");

        anoAluno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        gerarXml.setBackground(new java.awt.Color(255, 51, 51));
        gerarXml.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        gerarXml.setText("Gerar XML");

        removerAluno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        removerAluno.setText("Remover");
        removerAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAlunoActionPerformed(evt);
            }
        });

        tabelaAlunos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ano", "Disciplina"
            }
        ));
        jScrollPane3.setViewportView(tabelaAlunos);

        fechar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        listabox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaboxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(GravarAluno)
                                            .addGap(18, 18, 18)
                                            .addComponent(limparAlunos))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel4))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                .addComponent(anoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                .addComponent(listabox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(removerAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(fechar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(cadastrarDisciplina))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(gerarXml)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(cadastrarDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(gerarXml))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(anoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(listabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparAlunos)
                            .addComponent(removerAluno)
                            .addComponent(fechar)
                            .addComponent(GravarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anoAluno, nomeAluno});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {GravarAluno, cadastrarDisciplina, fechar, gerarXml, limparAlunos, removerAluno});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GravarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarAlunoActionPerformed
        // TODO add your handling code here:

        Aluno aluno = new Aluno();
        aluno.setNome(nomeAluno.getText());
        aluno.setAno((String) anoAluno.getText());
        aluno.setDisciplina(disciplinasAluno.get(listabox.getSelectedIndex()));
        this.tabelaAlunos.setModel(modelo);
        modelA.addElement(aluno.getNome());
        modelo.addColumn("nome");
        modelo.addColumn("ano");
        modelo.addColumn("disciplina");
        modelo.addRow(new Object[]{nomeAluno.getText(), anoAluno.getText(), aluno.getDisciplina().getNome()});
        alunos.add(aluno);
        nomeAluno.setText("");
        anoAluno.setText("");


    }//GEN-LAST:event_GravarAlunoActionPerformed

    private void chamarTelaCadDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamarTelaCadDisciplina
        FrmDisciplinaModal frmCadDisciplina;
        frmCadDisciplina = new FrmDisciplinaModal(pai, true);
        frmCadDisciplina.setVisible(true);
    }//GEN-LAST:event_chamarTelaCadDisciplina

    private void limparAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunosActionPerformed
        // TODO add your handling code here:
        nomeAluno.setText("");
        anoAluno.setText("");


    }//GEN-LAST:event_limparAlunosActionPerformed

    private void removerAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAlunoActionPerformed
        // TODO add your handling code here:
        int index = tabelaAlunos.getSelectedRow();

        if ((modelo.getRowCount() > 0) && (index >= 0)) {

            alunos.remove(index);
            Object remove;
            remove = modelo.getValueAt(index, 0);
            modelo.removeRow(index);
            JOptionPane.showMessageDialog(null, remove.toString() + " foi removido com sucesso ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma aluno ");

        }


    }//GEN-LAST:event_removerAlunoActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void listaboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaboxMouseClicked
        // TODO add your handling code here:
        listabox.removeAllItems();
        disciplinasAluno = Disciplina.getDisciplinas();
        for (Disciplina obj : disciplinasAluno) {
            listabox.addItem(obj.getNome());
    }//GEN-LAST:event_listaboxMouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadAlunoModal dialog = new FrmCadAlunoModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GravarAluno;
    private javax.swing.JTextField anoAluno;
    private javax.swing.JButton cadastrarDisciplina;
    private javax.swing.JButton fechar;
    private javax.swing.JButton gerarXml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton limparAlunos;
    private javax.swing.JComboBox<String> listabox;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JButton removerAluno;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
