/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Disciplina;

/**
 *
 * @author Sujajeb
 */
public class FrmCadAlunoModal extends javax.swing.JDialog {

    java.awt.Frame pai;
    private DefaultTableModel modelo = new DefaultTableModel();
    private final List<Aluno> alunos = new ArrayList<Aluno>();
    private List<Disciplina> disciplinasAluno = Disciplina.getDisciplinas();
    private String xml1 = null;

    /**
     * Creates new form FrmCadClienteModal
     */
    public FrmCadAlunoModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pai = parent;

        initComponents();
        modelo.addColumn("Aluno");
        modelo.addColumn("Ano");
        modelo.addColumn("Disciplina");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        GravarAluno = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cadastrarDisciplina = new javax.swing.JButton();
        limparAlunos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        anoAluno = new javax.swing.JTextField();
        gerarXml = new javax.swing.JButton();
        removerAluno = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        fechar = new javax.swing.JButton();
        listabox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        abrirXML = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de alunos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Ano:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Nome:");

        nomeAluno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        GravarAluno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        GravarAluno.setText("Gravar");
        GravarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Disciplina:");

        cadastrarDisciplina.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cadastrarDisciplina.setText("Cadastrar Disciplina");
        cadastrarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamarTelaCadDisciplina(evt);
            }
        });

        limparAlunos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        limparAlunos.setText("Limpar");
        limparAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparAlunosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Cadastro de Alunos");

        anoAluno.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        gerarXml.setBackground(new java.awt.Color(255, 51, 51));
        gerarXml.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        gerarXml.setText("Gerar XML");
        gerarXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarXmlActionPerformed(evt);
            }
        });

        removerAluno.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        removerAluno.setText("Remover");
        removerAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAlunoActionPerformed(evt);
            }
        });

        tabelaAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        tabelaAlunos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ano", "Disciplina"
            }
        ));
        tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAlunos);

        fechar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharfecharActionPerformed(evt);
            }
        });

        listabox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaboxMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        abrirXML.setBackground(new java.awt.Color(255, 204, 51));
        abrirXML.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        abrirXML.setText("Abrir XML");
        abrirXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(listabox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(anoAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                .addComponent(nomeAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(cadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(GravarAluno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(limparAlunos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removerAluno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(fechar)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(abrirXML)
                                .addComponent(gerarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anoAluno, listabox, nomeAluno});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fechar, jButton1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abrirXML, gerarXml});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(listabox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparAlunos)
                            .addComponent(removerAluno)
                            .addComponent(fechar)
                            .addComponent(GravarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gerarXml, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(abrirXML)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anoAluno, nomeAluno});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {GravarAluno, fechar, jButton1, limparAlunos, removerAluno});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {abrirXML, gerarXml});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GravarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarAlunoActionPerformed
        // TODO add your handling code here:
        Aluno aluno = new Aluno();
        aluno.setNome(nomeAluno.getText());
        aluno.setAno((String) anoAluno.getText());
        aluno.setDisciplina(disciplinasAluno.get(listabox.getSelectedIndex()));
        tabelaAlunos.setModel(modelo);
        modelo.addRow(new Object[]{nomeAluno.getText(), anoAluno.getText(), aluno.getDisciplina().getNome()});
        alunos.add(aluno);
        nomeAluno.setText("");
        anoAluno.setText("");
    }//GEN-LAST:event_GravarAlunoActionPerformed

    private void chamarTelaCadDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamarTelaCadDisciplina
        FrmDisciplinaModal frmCadDisciplina;
        frmCadDisciplina = new FrmDisciplinaModal(pai, true);
        frmCadDisciplina.setVisible(true);
    }//GEN-LAST:event_chamarTelaCadDisciplina

    private void limparAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparAlunosActionPerformed
        // TODO add your handling code here:
        nomeAluno.setText("");
        anoAluno.setText("");
    }//GEN-LAST:event_limparAlunosActionPerformed

    private void removerAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAlunoActionPerformed
        // TODO add your handling code here:
        int index = tabelaAlunos.getSelectedRow();
        if ((modelo.getRowCount() > 0) && (index >= 0)) {

            alunos.remove(index);
            Object remove;
            remove = modelo.getValueAt(index, 0);
            modelo.removeRow(index);
            nomeAluno.setText("");
            anoAluno.setText("");
            JOptionPane.showMessageDialog(null, remove.toString() + " foi removido com sucesso ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma aluno ");
        }
    }//GEN-LAST:event_removerAlunoActionPerformed

    private void fecharfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharfecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_fecharfecharActionPerformed

    private void listaboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaboxMouseClicked
        // TODO add your handling code here:
        listabox.removeAllItems();
        disciplinasAluno = Disciplina.getDisciplinas();
        for (Disciplina obj : disciplinasAluno) {
            listabox.addItem(obj.getNome());
    }//GEN-LAST:event_listaboxMouseClicked
    }
    private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
        // TODO add your handling code here:
        int index = tabelaAlunos.getSelectedRow();
        if ((modelo.getRowCount() > 0) && (index >= 0)) {
            nomeAluno.setText(alunos.get(index).getNome());
            anoAluno.setText(alunos.get(index).getAno());
            nomeAluno.setText(alunos.get(index).getNome());
            listabox.removeAllItems();
            listabox.addItem(alunos.get(index).getDisciplina().getNome());
        }


    }//GEN-LAST:event_tabelaAlunosMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        int index = tabelaAlunos.getSelectedRow();
        if ((modelo.getRowCount() > 0) && (index >= 0)) {

            alunos.get(index).setNome(nomeAluno.getText());
            alunos.get(index).setAno((String) anoAluno.getText());
            alunos.get(index).setDisciplina(disciplinasAluno.get(listabox.getSelectedIndex()));
            tabelaAlunos.setModel(modelo);
            modelo.removeRow(index);
            modelo.insertRow(index, new Object[]{nomeAluno.getText(), anoAluno.getText(), alunos.get(index).getDisciplina().getNome()});
            nomeAluno.setText("");
            anoAluno.setText("");
            Object edit;
            edit = modelo.getValueAt(index, 0);

            JOptionPane.showMessageDialog(null, edit.toString() + " foi editado com sucesso ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma aluno ");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void gerarXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarXmlActionPerformed
        // TODO add your handling code here:

        XStream xstream = new XStream(new DomDriver());

       // for (Aluno aluno : alunos) {
         //   String xml = xstream.toXML(alunos);
           // xml1 = xml1 + xml;
        //}
            String xml = xstream.toXML(alunos);

        System.out.println(xml);
        File file = new File("C:\\Users\\Sujajeb\\Desktop\\arquivoXML.xml");

        try (PrintWriter print = new PrintWriter(file)) {
            print.write(xml);
            print.flush();
            print.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmCadAlunoModal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gerarXmlActionPerformed

    private void abrirXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirXMLActionPerformed
        try {
            // TODO add your handling code here:
            FileReader leitor= new  FileReader("C:\\Users\\Sujajeb\\Desktop\\arquivoXML.xml");
            XStream xstream = new XStream(new DomDriver());
            List <Aluno> alunos = new ArrayList();
            alunos =(ArrayList) xstream.fromXML(leitor);

            for (Aluno inserir: alunos){
                this.tabelaAlunos.setModel(modelo);
                modelo.addRow(new Object[]{inserir.getNome(), inserir.getAno(), inserir.getDisciplina().getNome()});
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmCadAlunoModal.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_abrirXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadAlunoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadAlunoModal dialog = new FrmCadAlunoModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GravarAluno;
    private javax.swing.JButton abrirXML;
    private javax.swing.JTextField anoAluno;
    private javax.swing.JButton cadastrarDisciplina;
    private javax.swing.JButton fechar;
    private javax.swing.JButton gerarXml;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton limparAlunos;
    private javax.swing.JComboBox<String> listabox;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JButton removerAluno;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables
}
